name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zkamvar/test-docker-site:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/site
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: hi
        run: Rscript -e "corefast::hello(); list.files(); list.files('/site')"
      - id: build
        run: Rscript -e "corefast::build('/site')"
      - id: list-outputs
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@umass.edu"
          git config --global --add safe.directory /__w/test-docker-site/test-docker-site
          git remote set-url origin \
          https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git worktree add pages gh-pages
          echo "-----source"
          ls
          echo "-----output"
          ls _site
          echo "-----pages"
          ls pages
          cp -R _site/* pages
          echo "-----adding stuff"
          cd pages && git add . && git commit --amend -m 'deploy' && git push --force
          cd -
          git worktree remove gh-pages

  

