name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zkamvar/test-docker-site:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/site
    steps:
      - id: hi
        run: Rscript -e "corefast::hello()" && Rscript -e "list.files('site')"
      - id: build
        run: Rscript -e "corefast::build('site')"

  

