name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zkamvar/test-docker-site:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/site
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: checkout-pages
        uses: actions/checkout@v4
        with:
          branch: gh-pages
          path: _site
      - id: hi
        run: Rscript -e "corefast::hello(); list.files(); list.files('/site')"
      - id: build
        run: Rscript -e "corefast::build('/site')"
      - id: list-outputs
        run: |
          echo "source"
          ls
          echo "output"
          ls _site
          echo "git status"
          (cd _site && git status)

  

