name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zkamvar/test-docker-site:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/site
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: hi
        run: Rscript -e "corefast::hello(); list.files(); list.files('/site')"
      - id: build
        run: Rscript -e "corefast::build('/site')"
      - id: checkout-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: pages
      - id: list-outputs
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@umass.edu"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          echo "-----source"
          ls
          echo "-----output"
          ls _site
          echo "-----pages"
          ls pages
          cp -R _site/* pages
          echo "-----adding stuff"
          cd pages && git add . && git commit --amend -m 'deploy' && git push --force

  

