name: "Build predtimechart dashboard"
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "17 19 * * *"

permissions:
  contents: write
jobs:
  repos:
    name: "Get list of dashboard repositories"
    env:
      APP_ID: ${{ vars.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.repos.outputs.repos }}
      slug: ${{ steps.repos.outputs.slug }}
      id: ${{ steps.repos.outputs.id }}
      email: ${{ steps.repos.outputs.email }}
      token: ${{ steps.token.outputs.token }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            requirements.txt
            appHelper.py
            getInstallations.py
      - id: setup-snake
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - id: install
        run: pip install -r requirements.txt
      - id: repos
        run: python getInstallations.py
  build-data:
    name: "Generate PredTimeChart data"
    runs-on: ubuntu-latest
    needs: [repos]
    continue-on-error: true
    strategy: 
      matrix: 
        site: ${{ fromJSON(needs.repos.outputs.repos) }}
    steps:
      - id: id
        run: |
          owner="${{ matrix.site.owner }}"
          name="${{ matrix.site.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-data" >> $GITHUB_OUTPUT
      - id: setup-snake
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - id: install-predtimechart-tool
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/hubverse-org/hub-dashboard-predtimechart
      - id: checkout-pages
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.id.outputs.repo }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            predtimechart-config.yml
            site-config.yml
      - id: get-repo-name
        run: |
          yq eval '.hub' site-config.yml \
          | sed -E -e 's+(https://github.com/|^)+repo=+' \
          | sed -E -e 's+[/]$++' >> $GITHUB_OUTPUT
      - id: clone-repo
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.get-repo-name.outputs.repo }}
          path: 'repo'
      - id: json-lives
        run: |
          ls -larth repo/
          ls -larth
          mkdir -p out/targets/
          mkdir -p out/forecasts/
          ptc_generate_FluSight_targets \
            repo \
            out/targets
          ptc_generate_json_files \
            repo \
            predtimechart-config.yml \
            out/predtimechart-options.json \
            out/forecasts
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
          path: 'out/'
  build-site:
    name: "Generate Static Site"
    runs-on: ubuntu-latest
    needs: [repos]
    continue-on-error: true
    strategy: 
      matrix: 
        site: ${{ fromJSON(needs.repos.outputs.repos) }}
    container:
      image: ghcr.io/zkamvar/test-docker-site:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/site
    steps:
      - id: id
        run: |
          owner="${{ matrix.site.owner }}"
          name="${{ matrix.site.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-site" >> $GITHUB_OUTPUT
      - id: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.id.outputs.repo }}
      - id: build-site
        run: bash -x /render.sh "${{ matrix.site.owner }}" "${{ matrix.site.name }}" ptc/data
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
          path: '/site/pages/'
  push-data:
    name: "Push Data to ptc/data branch"
    runs-on: ubuntu-latest
    needs: [repos, build-data]
    continue-on-error: true
    strategy: 
      matrix: 
        site: ${{ fromJSON(needs.repos.outputs.repos) }}
    steps:
      - id: checkout-this-here-repo-scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts
      - id: id
        run: |
          owner="${{ matrix.site.owner }}"
          name="${{ matrix.site.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-data" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ matrix.site.owner }}
          repositories: ${{ matrix.site.name }}
      - id: check-branch
        env:
          GH_TOKEN: ${{ github.token }}
        name: "check for gh-pages branch and create if needed"
        run: | 
          bash -x "${{ github.workspace }}/scripts/check-branch.sh" \
            "ptc/data" \
            "${{ steps.id.outputs.repo }}" \
            "${{ needs.repos.outputs.slug }}" \
            "${{ needs.repos.outputs.email }}" \
            "${{ steps.token.outputs.token }}"
      - id: checkout-pages
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.id.outputs.repo }}
          ref: ptc/data
          path: 'data'
          token: ${{ steps.token.outputs.token }}
      - id: fetch-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
      - id: publish
        run: | 
          ls -larth
          bash -x "${{ github.workspace }}/scripts/pushit.sh" \
            "ptc/data" \
            "${{ steps.id.outputs.repo }}" \
            "${{ needs.repos.outputs.slug }}" \
            "${{ needs.repos.outputs.email }}" \
            "${{ steps.token.outputs.token }}"
  push-site:
    name: "Push Static Site to gh-pages branch"
    runs-on: ubuntu-latest
    needs: [repos, build-site]
    continue-on-error: true
    strategy: 
      matrix: 
        site: ${{ fromJSON(needs.repos.outputs.repos) }}
    steps:
      - id: checkout-this-here-repo-scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts
      - id: id
        run: |
          owner="${{ matrix.site.owner }}"
          name="${{ matrix.site.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-site" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ matrix.site.owner }}
          repositories: ${{ matrix.site.name }}
      - id: check-branch
        env:
          GH_TOKEN: ${{ github.token }}
        name: "check for gh-pages branch and create if needed"
        run: | 
          bash -x "${{ github.workspace }}/scripts/check-branch.sh" \
            "gh-pages" \
            "${{ steps.id.outputs.repo }}" \
            "${{ needs.repos.outputs.slug }}" \
            "${{ needs.repos.outputs.email }}" \
            "${{ steps.token.outputs.token }}"
      - id: checkout-pages
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.id.outputs.repo }}
          ref: gh-pages
          path: 'pages'
          token: ${{ steps.token.outputs.token }}
      - id: fetch-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
      - id: publish
        run: | 
          bash -x "${{ github.workspace }}/scripts/pushit.sh" \
            "gh-pages" \
            "${{ steps.id.outputs.repo }}" \
            "${{ needs.repos.outputs.slug }}" \
            "${{ needs.repos.outputs.email }}" \
            "${{ steps.token.outputs.token }}"

  

