name: CI
on:
  push:
    branches: [ main ]

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zkamvar/test-docker-site:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/site
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: build
        run: quarto render
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: 'site'
          path: '/site'
  push:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - id: checkout-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - id: fetch-artifact
        uses: actions/download-artifact@v4
        with:
          name: 'site'
      - id: publish
        run: |
          echo "-----source"
          ls
          # echo "-----output"
          # ls _site
          # echo "-----pages"
          # ls pages
          # cp -R _site pages
          echo "-----adding stuff"
          # cd pages
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id}}+${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin \
          https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add . && git commit --amend -m 'deploy' && git push --force
          # cd -

  

